### ISSUE TITLE
No http link to repo in package.json

### ISSUE THREAD

**Issue by Steve-Mcl** [yadomi/node-red-contrib-philipshue-events#10]
Hi, package.json does not have a link back to this repo making it difficult for users to locate it (for leaving feedback/issues)

Typically, a package would contain...

```json
    "homepage": "https://github.com/yadomi/node-red-contrib-philipshue-events/readme.md",
    "repository": {
        "type": "git",
        "url": "git+"https://github.com/yadomi/node-red-contrib-philipshue-events"
    },
    "bugs": {
        "url": "https://github.com/yadomi/node-red-contrib-philipshue-events/issues/"
    },
```

Additionally (and I am unsure if there is something odd in your readme.md, related to missing `homepage`, a flows lib issue or a combination of the above) but there is no documentation shown in the flow library (see here: https://flows.nodered.org/node/@yadomi/node-red-contrib-philipshue-events)

Thanks.

**Comment by yadomi** [comment]
Thanks for the report, I’ve added the repository entry in the package.json as well as the homepage entry, should be fixed now.

However, for some reasons, nodered.org still asks for node and node-red version and bugs entry even if they’re present in the package.json (https://flows.nodered.org/node/@yadomi/node-red-contrib-philipshue-events/scorecard#)

https://github.com/yadomi/node-red-contrib-philipshue-events/blob/2ba09f3fb9ba15376d859a7ce01fd5215a3100e4/package.json#L10-L13

https://github.com/yadomi/node-red-contrib-philipshue-events/blob/2ba09f3fb9ba15376d859a7ce01fd5215a3100e4/package.json#L18-L20

https://github.com/yadomi/node-red-contrib-philipshue-events/blob/2ba09f3fb9ba15376d859a7ce01fd5215a3100e4/package.json#L21-L22

**Comment by yadomi** [comment]
Fixed in https://github.com/yadomi/node-red-contrib-philipshue-events/releases/tag/v1.5.1 (turn out repository + bugs property don't mix well for flows.nodered.org )

See: https://flows.nodered.org/node/@yadomi/node-red-contrib-philipshue-events
