### ISSUE TITLE
Feature Request: Add name to the events config

### ISSUE THREAD

**Issue by bond2k** [yadomi/node-red-contrib-philipshue-events#20]
Currently the events config are shown with "Hue" and the IP address. Would be great if it could also have a name to distinguish them as I don't remember this IP address belongs to which Hue Hub. :)

**Comment by andesse** [comment]
When I remember right it should be possible to name the setup config.
If not, just use a comment node, write it down and place it on top:)

**Comment by yadomi** [comment]
@bond2k Indeed it was missing I thought it was already possible. I've released [v1.6.0](https://www.npmjs.com/package/@yadomi/node-red-contrib-philipshue-events) that adds the possibility to set a label on both node (PR #22).

**Comment by andesse** [comment]
The configs already could have different names, what in my opinion was finde, but thanks.

**Comment by bond2k** [comment]
Great, thanks.
