### ISSUE TITLE
API Stable

### ISSUE THREAD

**Issue by darkzbaron** [yadomi/node-red-contrib-philipshue-events#3]
Hi there, I am having a hard time getting the events from my bridge, is it the same for you? I am just using Postman for debug for now

**Comment by yadomi** [comment]
The API is pretty stable on my side, do you have any use case I can try to reproduce ? Also make sure your bridge [version is at least 1948086000](https://developers.meethue.com/develop/hue-api-v2/). 

This node use the `/eventstream/clip/v2` endpoint but I don't think Postman handles `EventStream` yet.

**Comment by yadomi** [comment]
I'm closing the issue, feel free to re-open if there is an actual issue with the nodes
